StudentManagementSystem/Controllers/BankController.cs
using AutoMapper;
using SM.BLL;
using SM.Models;
using StudentManagementSystem.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentManagementSystem.Controllers
{
    public class BankController : Controller
    {
        BankManager _bankManager = new BankManager();

        [HttpGet]
        public ActionResult Add()
        {
            if ((string)Session["user"] != "admin")
            {
                return RedirectToAction("../Home/Login");
            }
            BankVM bankVM = new BankVM();
            bankVM.Banks = _bankManager.GetAll();
            return View(bankVM);
        }

        [HttpPost]
        public ActionResult Add(BankVM bankVM)
        {
            Bank bank = Mapper.Map<Bank>(bankVM);
            if (_bankManager.Add(bank))
            {
                TempData["saved"] = "Bank added successfully!";
                return RedirectToAction("Add");
            }
            TempData["failed"] = "Failed to add";
            return View();
        }

        public JsonResult Delete(int id)
        {
            _bankManager.Delete(id);
            return null;
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            if ((string)Session["user"] != "admin")
            {
                return RedirectToAction("../Home/Login");
            }
            var bankVM = Mapper.Map<BankVM>(_bankManager.GetById(id));
            return View(bankVM);
        }

        [HttpPost]
        public ActionResult Update(BankVM bankVM)
        {
            Bank bank = Mapper.Map<Bank>(bankVM);
            if (_bankManager.Update(bank))
            {
                TempData["updated"] = "Updated successfully";
                return RedirectToAction("Add");

            }
            TempData["failed"] = "Failed to update";
            return View();
        }

        public ActionResult Details(int id)
        {
            if ((string)Session["user"] != "admin")
            {
                return RedirectToAction("../Home/Login");
            }
            StudentManager studentManager = new StudentManager();
            var bank = _bankManager.GetById(id);
            BankVM bankVM = Mapper.Map<BankVM>(bank);
            bankVM.BankAccounts = studentManager.GetByBank(id);
            return View(bankVM);
        }

    }
}

StudentManagementSystem/Controllers/CityController.cs
using AutoMapper;
using SM.BLL;
using SM.Models;
using StudentManagementSystem.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentManagementSystem.Controllers
{
    public class CityController : Controller
    {
        CityManager _cityManager = new CityManager();
        CountryManager _countryManager = new CountryManager();
        
        [HttpGet]
        public ActionResult Add()
        {
            if ((string)Session["user"] != "admin")
            {
                return RedirectToAction("../Home/Login");
            }
            CityVM cityVM = new CityVM();
            cityVM.Cities = _cityManager.GetAll();
            cityVM.CountryLookup = _countryManager.Lookup();
            return View(cityVM);
        }

        [HttpPost]
        public ActionResult Add(CityVM cityVM)
        {
            City city = Mapper.Map<City>(cityVM);
            if (_cityManager.Add(city))
            {
                TempData["saved"] = "Saved Successfully";
                return RedirectToAction("Add");
            }
            return RedirectToAction("Add");
        }

        public JsonResult Delete(int id)
        {
            _cityManager.Delete(id);
            return null;
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            if ((string)Session["user"] != "admin")
            {
                return RedirectToAction("../Home/Login");
            }
            var city = _cityManager.GetById(id);
            CityVM cityVM = Mapper.Map<CityVM>(city);
            cityVM.CountryLookup = _countryManager.Lookup();
            return View(cityVM);
        }

        [HttpPost]
        public ActionResult Update(CityVM cityVM)
        {
            City city = Mapper.Map<City>(cityVM);
            if (_cityManager.Update(city))
            {
                TempData["updated"] = "Updated sauccessfully!";
                return RedirectToAction("Add");
            }
            return View();
        }
        public ActionResult Details(int id)
        {
            if ((string)Session["user"] != "admin")
            {
                return RedirectToAction("../Home/Login");
            }
            StudentManager studentManager = new StudentManager();
            var city = _cityManager.GetById(id);
            CityVM cityVM = Mapper.Map<CityVM>(city);
            cityVM.Students = studentManager.GetByCity(id);
            return View(cityVM);
        }
    }
}

StudentManagementSystem/Controllers/CountryController.cs
using AutoMapper;
using SM.BLL;
using SM.Models;
using StudentManagementSystem.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentManagementSystem.Controllers
{
    public class CountryController : Controller
    {
        CountryManager _countryManager = new CountryManager();
        // GET: Country
        [HttpGet]
        public ActionResult Add()
        {
            if ((string)Session["user"] != "admin")
            {
                return RedirectToAction("../Home/Login");
            }
            CountryVM countryVM = new CountryVM();
            countryVM.Countries = _countryManager.GetAll();
            return View(countryVM);
        }

        [HttpPost]
        public ActionResult Add(CountryVM countryVM)
        {
            Country country = Mapper.Map<Country>(countryVM);

            if (_countryManager.Add(country))
            {
                TempData["saved"] = "Country added successfully!";
                CountryVM countryView = new CountryVM();
                countryView.Countries = _countryManager.GetAll();
                return View(countryView);

            }
            return RedirectToAction("Add");
        }

        public JsonResult Delete(int id)
        {
            _countryManager.Delete(id);
            return null;
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            if ((string)Session["user"] != "admin")
            {
                return RedirectToAction("../Home/Login");
            }
            var country = _countryManager.GetById(id);
            CountryVM countryVM = Mapper.Map<CountryVM>(country);
            return View(countryVM);
        }

        [HttpPost]
        public ActionResult Update(CountryVM countryVM)
        {
            Country country = Mapper.Map<Country>(countryVM);
            if (_countryManager.Update(country))
            {
                TempData["updated"] = "Updated Successfully!";
                return RedirectToAction("Add");
            }
            TempData["failed"] = "Failed to update!";
            return RedirectToAction("Update");
        }

        public ActionResult Details(int id)
        {
            if ((string)Session["user"] != "admin")
            {
                return RedirectToAction("../Home/Login");
            }
            StudentManager studentManager = new StudentManager();
            var country = _countryManager.GetById(id);
            CountryVM countryVM = Mapper.Map<CountryVM>(country);
            countryVM.Students = studentManager.GetByCountry(id);
            return View(countryVM);
        }
    }
}

StudentManagementSystem/Controllers/SesionController.cs
using AutoMapper;
using SM.BLL;
using SM.Models;
using StudentManagementSystem.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentManagementSystem.Controllers
{
    public class SesionController : Controller
    {

        SessionManager _sessionManager = new SessionManager();

        [HttpGet]
        public ActionResult Add()
        {
            if ((string)Session["user"] != "admin")
            {
                return RedirectToAction("../Home/Login");
            }
            SesionVM sessionVM = new SesionVM();
            sessionVM.Sesions = _sessionManager.GetAll();
            return View(sessionVM);
        }
        [HttpPost]
        public ActionResult Add(SesionVM sessionVM)
        {
            Sesion session = Mapper.Map<Sesion>(sessionVM);
            if (_sessionManager.Add(session))
            {
                TempData["saved"] = "Saved Successfully!";
                return RedirectToAction("Add");
            }
            return View();
        }

        public JsonResult Delete(int id)
        {
            _sessionManager.Delete(id);
            return null;
        }

        [HttpGet]

        public ActionResult Update(int id)
        {
            if ((string)Session["user"] != "admin")
            {
                return RedirectToAction("../Home/Login");
            }
            var session = _sessionManager.GetById(id);
            SesionVM sessionVM = Mapper.Map<SesionVM>(session);
            return View(sessionVM);
        }

        [HttpPost]
        public ActionResult Update(SesionVM sesionVM)
        {
            Sesion session = Mapper.Map<Sesion>(sesionVM);
            if (_sessionManager.Update(session))
            {
                TempData["updated"] = "Updated successfully!";
                return RedirectToAction("Add");
            }
            TempData["failed"] = "Failed to update";
            return View();
        }

        public ActionResult Details(int id)
        {
            if ((string)Session["user"] != "admin")
            {
                return RedirectToAction("../Home/Login");
            }
            StudentManager studentManager = new StudentManager();
            var sesion = _sessionManager.GetById(id);
            SesionVM sesionVM = Mapper.Map<SesionVM>(sesion);
            sesionVM.Students = studentManager.GetBySession(id);
            return View(sesionVM);
        }
    }
}

StudentManagementSystem/Views/Shared/View.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

StudentManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content")
         @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Scripts/JqueryUI/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />
</head>
<body>
    <div class="conteiner-fluid">
        <div class="sidebar col-lg-2">
            <h4>@Session["userName"]</h4>
            <br /><br />
            <li class="col-lg-12" style="background:#484848; border:none"><a href="/Home/Logout" style="color:#f5ff0c; font-weight:bold;">Logout</a></li>
            <li class="col-lg-12" style="background:#168d7a; border-radius: 8px 8px 0px 0;"><span style="margin-right:5px;" class="glyphicon glyphicon-home"></span> @Html.ActionLink("Dashboard", "Dashboard", "Home")</li>
            <li class="col-lg-12">@Html.ActionLink("Add New Student", "Add", "Student")</li>
            <li class="col-lg-12">@Html.ActionLink("Add New Department", "Add", "Department")</li>
            <li class="col-lg-12">@Html.ActionLink("Add New Session", "Add", "Sesion")</li>
            <li class="col-lg-12">@Html.ActionLink("Add New Semister", "Add", "Semister")</li>
            <li class="col-lg-12">@Html.ActionLink("Add New Country", "Add", "Country")</li>
            <li class="col-lg-12">@Html.ActionLink("Add New City", "Add", "City")</li>
            <li class="col-lg-12">@Html.ActionLink("Add New Bank", "Add", "Bank")</li>
        </div>
        <div class="content col-lg-10">
            @RenderBody()
            
        </div>

    </div>

     @Scripts.Render("~/bundles/jquery")
     @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/JqueryUI/jquery-ui.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

StudentManagementSystem/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Scripts/JqueryUI/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />
</head>
<body>
    <div class="conteiner-fluid">
        <div class="sidebar col-lg-2">
            <h4>@Session["userName"]</h4>
            <br /><br />
            <li class="col-lg-12">@Html.ActionLink("Logout", "Logout", "Home")</li>
            <li class="col-lg-12"><a href="/Student/ChangePassword?id=@TempData["StudentId"]">Change Password &nbsp; &nbsp;</a></li>
           
        </div>
        <div class="content col-lg-10">
            @RenderBody()

        </div>

    </div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/modernizr-2.6.2.js"></script>
<script src="~/Scripts/JqueryUI/jquery-ui.min.js"></script>
@RenderSection("scripts", required: false)
</body>
</html>